# Generated by Django 4.0.3 on 2022-04-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companypurchase',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='companypurchasemedicine',
            old_name='medicine_id',
            new_name='medicine',
        ),
        migrations.RenameField(
            model_name='companypurchasemedicine',
            old_name='purchase_id',
            new_name='purchase',
        ),
        migrations.RenameField(
            model_name='customerpayment',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customerpurchase',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customerpurchasemedicine',
            old_name='medicine_id',
            new_name='medicine',
        ),
        migrations.RenameField(
            model_name='customerpurchasemedicine',
            old_name='purchase_id',
            new_name='purchase',
        ),
    ]
