# Generated by Django 4.0.3 on 2022-04-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_rename_company_id_companypurchase_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='type_id',
            new_name='type',
        ),
    ]
