# Generated by Django 4.0.3 on 2022-04-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_rename_type_id_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='medicine_pics'),
        ),
        migrations.AlterField(
            model_name='companypurchase',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='medicine.company'),
        ),
        migrations.AlterField(
            model_name='companypurchasemedicine',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicine.companypurchase'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='medicine.customer'),
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='medicine.customer'),
        ),
        migrations.AlterField(
            model_name='customerpurchasemedicine',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicine.customerpurchase'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicine.medicinetype'),
        ),
    ]
